decliner:
  description: >
    Inform the user that their request is outside the scope of Formula 1 topics.
    Politely suggest they ask something related to Formula 1 instead.
  expected_output: >
    A short, friendly refusal message.
  agent: outOfScope